markdown: kramdown
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: songpeace.github.io
title: 首页
description: 
author: songworld
email: songworld#126.com
github: songpeace

config:
  js_dir:
  img_dir:
  css_dir:
