markdown: redcarpet
  redcarpet:
    extensions:
      - hard_wrap
      - no_intra_emphasis
      - autolink
      - strikethrough
      - fenced_code_blocks
      - with_toc_data
      - tables
      - underline
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: songpeace.github.io
title: 首页
description: Android, Cocos2d, Java Web, Linux, reading...
author: Steven Pan
email: songworld#126.com
github: songpeace

config:
  js_dir:
  img_dir:
  css_dir:
