markdown: kramdown
permalink: /:categories/:title.html
url: 
lsi: false
pygments:
highlighter: rouge
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: familyxin.github.io
title: 首页
description: 
author: xinxin
email: familyxin#126.com
github: familyxin

config:
  js_dir:
  img_dir:
  css_dir:
